services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ivy-api
    restart: always
    env_file:
      - ./.env.development
    ports:
      - "8080:8080"
    environment:
      APP_PORT: ${APP_PORT}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SSL_MODE: ${SSL_MODE}
    networks:
      - ivy-network

networks:
  ivy-network:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
        - subnet: 2001:db8:1::/64
